apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dcqd67h0p-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-45806b09da.t3km.p3.openshiftapps.com/rhtap/rhtap-qe:9b26067b37e3dea9890b3850820bfa5e26dfb979@sha256:ccc2f91119ca694da36a2fc5f35c3bdb74cdd0d427915f9739ce7c45fddc5bf1
          name: container-image
